"""Query provenance for collected evidence (Milestone 4D-0).

Three concepts that this repository keeps strictly apart:

    observation identity      raw_payload_hash
    candidate association     candidate_id / research_run_id
    HOW the observation
    was found                 originating_queries  (this module)

This module owns only the third. It records which provider queries returned
an observation, so a later milestone can say "this observation came back
from query X, which was generated for candidate Y" rather than the much
weaker "something associated with candidate Y".

What provenance is
------------------

The NORMALIZED query string actually sent to the provider — the literal
argument passed to `search_listings` / `search_videos` / the keyword batch.
It is provider-request provenance. It is **not** necessarily the user's or
Milestone 1's original raw wording: `normalize_query` lowercases and
collapses whitespace before the request is made, and the raw candidate text
is never stored here. A consumer must not present these strings as words a
buyer typed.

What provenance is not
----------------------

It is metadata about retrieval, never about support. Knowing how a record
was found says nothing about how well the underlying claim is evidenced, so
provenance NEVER changes an evidence record's truth class and can never
upgrade UNKNOWN or INFERRED to OBSERVED.

It is also deliberately kept out of `raw_payload`. `raw_payload_hash` is the
identity of the observation itself, and every downstream deduplicator keys
on it. The same listing reached by two different queries is still one
listing and must still hash identically; embedding provenance in the payload
would split that identity and inflate every derived count.

Candidate filtering
-------------------

One query is often generated for several candidates, and one observation is
often returned by several queries. Attribution is therefore filtered to the
queries belonging to the candidate whose record is being written: another
candidate's query never appears on this candidate's evidence merely because
both queries happened to return the same observation.

`originating_query_shared` reports whether any of those queries was also
generated for a different candidate in the same run, so a shared query can
never read as evidence that it was uniquely generated for this candidate.
It is a boolean rather than a count on purpose: a number here would invite
being read as popularity, demand, reach, or market strength, none of which
a query-sharing tally measures.

Unknown versus empty
--------------------

    None    provenance UNKNOWN — recorded before this milestone, or by a
            path that does not capture it. Never reconstructed, never
            inferred from candidate text.
    ()      provenance known, and known to contain zero queries.

These are different facts and must never be collapsed.
"""

from uuid import UUID

# Bumped only if the meaning of a provenance field changes.
QUERY_PROVENANCE_VERSION = "query_provenance_v1"

LIMITATIONS = (
    "originating_queries records the NORMALIZED query sent to the provider, "
    "not the original raw candidate wording and not a phrase any buyer typed.",
    "Provenance describes how an observation was retrieved. It is never "
    "evidence about the observation's accuracy, and never changes a truth class.",
    "A query was generated by Milestone 1 as a hypothesis. That a query "
    "returned a result is not evidence that the result is relevant to the "
    "candidate; it only records how the result was reached.",
    "originating_query_shared reports query overlap between candidates in one "
    "run. It is not a measure of popularity, demand, reach, or competition.",
    "None means provenance is UNKNOWN; it is never backfilled for evidence "
    "collected before this milestone.",
)


def resolve_provenance(
    candidate_id: UUID,
    queries_for_observation: list[str],
    query_to_candidates: dict[str, list[UUID]],
) -> tuple[tuple[str, ...], bool]:
    """Provenance for one (candidate, observation) pair.

    Returns (originating_queries, originating_query_shared).

    `queries_for_observation` is every query that returned this observation,
    in arrival order. Only those also generated for `candidate_id` survive:
    that is the candidate filter. The result is deduplicated and sorted, so
    the same inputs always produce the same tuple however the results
    arrived, and re-delivery of a duplicate adds nothing.

    An observation reached only through other candidates' queries yields
    `()` — provenance known, containing no query of this candidate's own.
    That is a fact, not an absence, and is distinct from None.
    """
    own = {
        query
        for query in queries_for_observation
        if candidate_id in query_to_candidates.get(query, ())
    }
    shared = any(
        len(query_to_candidates.get(query, ())) > 1 for query in own
    )
    return tuple(sorted(own)), shared
